#!/usr/bin/env bash
# Copyright (C) 2017-2026 Smart code 203358507
#
# Brings up the watch party stack on your tailnet.
#
# Derives the origin from Tailscale rather than asking you to type it: an origin
# that does not match the browser exactly is the single most common way to end up
# with every WebSocket rejected and no useful error in the interface.

set -euo pipefail

cd "$(dirname "$0")"
REPO_ROOT="$(cd ../.. && pwd)"

# The macOS App Store build does not put the CLI on PATH.
TAILSCALE="$(command -v tailscale || true)"
if [ -z "$TAILSCALE" ] && [ -x /Applications/Tailscale.app/Contents/MacOS/Tailscale ]; then
    TAILSCALE=/Applications/Tailscale.app/Contents/MacOS/Tailscale
fi
if [ -z "$TAILSCALE" ]; then
    echo "error: tailscale CLI not found" >&2
    exit 1
fi

HTTP_PORT="${WATCH_PARTY_HTTP_PORT:-8123}"

if ! "$TAILSCALE" status >/dev/null 2>&1; then
    echo "error: Tailscale is not running. Start it, then re-run this." >&2
    exit 1
fi

# Trailing dot is part of the DNS name and must not reach the browser origin.
DNS_NAME="$("$TAILSCALE" status --json | python3 -c 'import json,sys; print(json.load(sys.stdin)["Self"]["DNSName"].rstrip("."))')"
if [ -z "$DNS_NAME" ]; then
    echo "error: could not determine this node MagicDNS name. Is MagicDNS enabled?" >&2
    exit 1
fi
ORIGIN="https://${DNS_NAME}"

if [ ! -d "${REPO_ROOT}/build" ]; then
    echo "error: ${REPO_ROOT}/build is missing. Run 'pnpm build' at the repository root first." >&2
    exit 1
fi

cat > .env <<ENV
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
WATCH_PARTY_ORIGIN=${ORIGIN}
WATCH_PARTY_HTTP_PORT=${HTTP_PORT}
ENV
echo "origin      ${ORIGIN}"

docker compose up -d --build
echo "stack       up on 127.0.0.1:${HTTP_PORT} (loopback only)"

# Wait for Caddy to answer before handing the port to Tailscale, so a first
# request does not land on a closed socket.
for _ in $(seq 1 30); do
    if curl -fsS -o /dev/null "http://127.0.0.1:${HTTP_PORT}/watch-party/healthz"; then
        break
    fi
    sleep 1
done

# Serve replaces any previous mapping for this port, so re-running is safe.
"$TAILSCALE" serve --bg --https 443 "http://127.0.0.1:${HTTP_PORT}"

echo
echo "  Watch party is live at ${ORIGIN}"
echo
echo "  Share it with your friend by sharing this machine from the Tailscale"
echo "  admin console, then send them that URL. They need no ports open."
echo
echo "  Stop serving:  ${TAILSCALE} serve --https 443 off"
echo "  Stop the stack: docker compose -f $(pwd)/compose.yml down"
